name: CheckForUpdates

on: #DO NOT CHANGE
  workflow_call: #https://docs.github.com/en/actions/learn-github-actions/reusing-workflows#creating-a-reusable-workflow
      inputs:
        templateRepo:
          required: true
          type: string
      secrets:
        PAT_RO:
          required: true


jobs:


  CheckForUpdates:
    #Dont put a template on a template
    if: ${{ !contains(github.event.repository.name , 'Template') }}
    runs-on: [self-hosted, linux, x64,L1]
    container:
       image: ghcr.io/setap2021/setapdocker   # Beware of versioning here GITHUB -- Some kind of magic here
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Clone Template Repo
      uses: actions/checkout@v2                            # 2
      with:
        repository:  ${{ inputs.templateRepo }}
        token: ${{ secrets.PAT_RO }}              # 4
        path: Template

    - name: Clone Student Repository (Latest)
      uses: actions/checkout@v2
      with:
        path: Student

    # This is a list of files that exist in the template
    # but may be altered by the students
    # do not overwrite student files
    # it is too late to update these
    - name: Remove Protected files from template
      run: |
        #change to template folder
        cd Template/
        #remove all that students may have altered
        # -f so that does not fail if not exist (multi repo)
        rm -fv CheckList.md
        rm -fv .pandoc.yml
        rm -fv Student.id ## Incase there is a testing ID in the system
        rm -fv Submit/* # No updates to the Submit folder
        rm -fv Portfolio.md
        rm -fv CW.md
        rm -fv header.md
        rm -fv declaration.md
        rm -fv .Ossonts/*.log
        rm -fv .Ossonts/RemoveReservedFiles.sh
        rm -fv .github/workflows/* # Never do workflows -- you don't have permissions (worker will fail)
      shell: bash

    - name: Overlay updated files (if any)
      run: |
        # Overlay files
        cp -vrf Template/* Student/
        cp -vrf Template/.Ossonts/* Student/.Ossonts/
        cp -vrf Template/.github/* Student/.github/
        cp -vrf Template/.vscode/* Student/.vscode/
        # End overlay
        tree Template/
        tree Student/
        # echo "Template folder"
        # git -C Template  status
        echo "Student folder changes list:"
        git -C Student status

      shell: bash

      # Commit any updated files
    - uses: EndBug/add-and-commit@v7
      with:
        message: "Assessment UPDATE"
        cwd: 'Student/'

      env:
        GITHUB_TOKEN: ${{ secrets.PAT_RO }}
